---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:619071307284:task-definition/spring-demo-task-def:1"
        LoadBalancerInfo:
          ContainerName: "spring-demo-ecr"
          ContainerPort: 8080
