version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - yum install -y jq maven
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=619071307284
      - REGION=us-east-1
      - REPO_NAME=spring-demo-ecr
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building the JAR file...
      - aws sts get-caller-identity
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

      - echo Creating Kubernetes deployment file...
      - mkdir -p k8s
      - sed "s|spring-demo-ecr|$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG|g" k8s/deployment.yaml > k8s/deployment.yaml
      - cp k8s/service.yaml k8s/service.yaml
      - echo Done.

artifacts:
  files:
    - k8s/deployment.yaml
    - k8s/service.yaml
