apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
  labels:
    app: spring-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: 619071307284.dkr.ecr.us-east-1.amazonaws.com/spring-demo-eks:latest
  # this will be replaced by buildspec
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
